### ISSUE TITLE
Horizontal line printing in vertical win

### ISSUE THREAD

**Issue by VishalArora14** [theoopsguy/MultiplayerTicTacToe#1]
Expected Behaviour : 
![expected_output](https://user-images.githubusercontent.com/87052028/235501498-76c38d5a-1e83-48de-a614-8eae2226362d.png)

Actual Behaviour : 
![actual_output](https://user-images.githubusercontent.com/87052028/235501553-78d121ad-e976-422e-a9e4-7024c7e5259a.png)

**Comment by theoopsguy** [comment]
Resolved.
